version: '3'

services:
  postgresql:
    image: postgres:14-alpine
    container_name: database
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - backend/star_burger/.env

  node:
    image: frontend:latest
    container_name: frontend
    command: ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
    volumes:
      - bundles_data:/frontend/bundles

  django:
    image: backend:latest
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn -b 0.0.0.0:8000 star_burger.wsgi:application"
    env_file:
      - backend/star_burger/.env
    volumes:
      - static_data:/star_burger/staticfiles
      - media_data:/star_burger/media
      - bundles_data:/star_burger/bundles
    depends_on:
      - postgresql
      - node

volumes:
  postgres_data:
  static_data:
  media_data:
  bundles_data: