version: '3'

services:
  postgresql:
    image: postgres:14-alpine
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - backend/star_burger/.env

  django:
    image: back:latest
    container_name: back
    working_dir: /star_burger/backend
    command: >
      sh -c "python manage.py migrate && gunicorn -b 0.0.0.0:8000 star_burger.wsgi:application"
    env_file:
      - backend/star_burger/.env
    volumes:
      - static_data:/star_burger/staticfiles
      - media_data:/star_burger/media
    depends_on:
      - migration
      - postgresql

  nginx:
    image: front:latest
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - static_data:/star_burger/staticfiles
      - media_data:/star_burger/media
    depends_on:
      - django

volumes:
  postgres_data:
  static_data:
  media_data:
