#!/bin/bash
cd /opt/star-burger/
git pull
cd backend/
pyenv activate star_burger
pip install -r requirements.txt
python manage.py collectstatic --noinput
python manage.py migrate
pyenv deactivate
cd ../frontend/
npm ci --dev
./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
systemctl restart star-burger.service
systemctl reload nginx.service
curl -H "X-Rollbar-Access-Token: $POST_SERVER_ACCESS_TOKEN" -H "Content-Type: application/json" -X POST 'https://api.rollbar.com/api/1/deploy' -d '{"environment": "production","revision": "'$(git rev-parse --short HEAD)'","local_username":"owwwl"}'
