# Generated by Django 4.2.7 on 2023-11-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodcartapp", "0045_rename_price_productorder_order_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("raw", "Необработанный"),
                    ("assembly", "Сборка"),
                    ("courier", "Передан курьеру"),
                    ("delivered", "Доставлен"),
                ],
                db_index=True,
                default="raw",
                max_length=30,
                verbose_name="Статус заказа",
            ),
        ),
    ]
