# Generated by Django 3.2.15 on 2023-12-11 10:10

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ("foodcartapp", "0058_auto_20231209_1323"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="registered_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 12, 11, 10, 10, 40, 737978, tzinfo=utc),
                verbose_name="Дата создания заказа",
            ),
        ),
        migrations.CreateModel(
            name="PO",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        db_index=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "order_price",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена заказа",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="foodcartapp.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="foodcartapp.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в заказе",
                "verbose_name_plural": "Товары в заказе",
            },
        ),
    ]
