# Generated by Django 3.2.15 on 2023-12-11 10:11

from django.db import migrations


def copy_productorder_to_po(apps, schema_editor):
    ProductOrder = apps.get_model("foodcartapp", "ProductOrder")
    PO = apps.get_model("foodcartapp", "PO")
    order_products = ProductOrder.objects.all()
    for order_product in order_products.iterator():
        PO.objects.create(
            order=order_product.order,
            product=order_product.product,
            quantity=order_product.quantity,
            order_price=order_product.order_price,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("foodcartapp", "0059_auto_20231211_1310"),
    ]

    operations = [
        migrations.RunPython(copy_productorder_to_po),
    ]
