# Generated by Django 3.2.15 on 2023-12-11 10:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ("foodcartapp", "0060_auto_20231211_1311"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="registered_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 12, 11, 10, 26, 17, 951625, tzinfo=utc),
                verbose_name="Дата создания заказа",
            ),
        ),
        migrations.DeleteModel(
            name="ProductOrder",
        ),
    ]
