# Generated by Django 3.2.15 on 2023-12-11 10:31

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ("foodcartapp", "0061_auto_20231211_1326"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        db_index=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "order_price",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена заказа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в заказе",
                "verbose_name_plural": "Товары в заказе",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="registered_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 12, 11, 10, 31, 19, 436905, tzinfo=utc),
                verbose_name="Дата создания заказа",
            ),
        ),
        migrations.DeleteModel(
            name="PO",
        ),
        migrations.AddField(
            model_name="productorder",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_products",
                to="foodcartapp.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AddField(
            model_name="productorder",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_products",
                to="foodcartapp.product",
                verbose_name="Товар",
            ),
        ),
    ]
