# Generated by Django 3.2.15 on 2024-04-05 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0062_auto_20231211_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 5, 11, 55, 15, 997682, tzinfo=utc), verbose_name='Дата создания заказа'),
        ),
    ]
