# Generated by Django 3.2.15 on 2023-12-09 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0004_alter_location_request_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='request_data',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 9, 9, 41, 14, 936002, tzinfo=utc), verbose_name='Дата запроса'),
        ),
    ]
