# Generated by Django 3.2.15 on 2024-04-05 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0010_alter_location_request_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='request_data',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 5, 11, 55, 15, 999464, tzinfo=utc), verbose_name='Дата запроса'),
        ),
    ]
