# Generated by Django 3.2.15 on 2023-11-16 11:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, verbose_name='Имя заказчика')),
                ('lastname', models.CharField(max_length=200, verbose_name='Фамилия заказчика')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='RU', verbose_name='Номер телефона')),
                ('adress', models.CharField(max_length=200, verbose_name='Адрес доставки')),
                ('products', models.ManyToManyField(related_name='orders', to='foodcartapp.Product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
