# Generated by Django 3.2.15 on 2023-11-16 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foodcartapp", "0038_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="adress",
            new_name="address",
        ),
    ]
