# Generated by Django 4.2.7 on 2023-11-27 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foodcartapp", "0044_auto_20231125_0336"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productorder",
            old_name="price",
            new_name="order_price",
        ),
    ]
