# Generated by Django 3.2.15 on 2023-12-09 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_alter_order_registrated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='registrated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 9, 9, 25, 48, 313557, tzinfo=utc), verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('not indicated', 'Не указано'), ('cash', 'Наличностью'), ('non-cash', 'Электронно')], db_index=True, default='not indicated', max_length=30, null=True, verbose_name='Способ оплаты'),
        ),
    ]
